[package]
name = "snarkvm-cosmwasm"
version = "3.8.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
cosmwasm = ["snarkvm-console/cosmwasm", "getrandom"]

[dependencies.snarkvm-console]
workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies.snarkvm-console]
workspace = true
features = ["cosmwasm"]

[target.'cfg(target_arch = "wasm32")'.dependencies.getrandom]
version = "0.2"
features = ["custom"]
optional = true
