[package]
name = "snarkvm-cosmwasm"
version = "3.8.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
cosmwasm = [ "snarkvm-console/cosmwasm", "getrandom" ]

[dependencies.snarkvm-console]
path = "../console"
version = "=3.8.0"

[dependencies.getrandom]
version = "0.2"
features = ["custom"]
optional = true
